[workspace]
resolver = "3"
members = ["juniper_relay_helpers", "juniper_relay_helpers_codegen", "juniper_relay_helpers_test"]

[workspace.dependencies]
juniper = { version = "0.17" }
base64 = "0.22"
uuid = "1"
