[workspace]
resolver = "3"
members = ["graphql_relay_helpers", "graphql_relay_helpers_codegen", "graphql_relay_helpers_test"]

[workspace.dependencies]
juniper = { version = "0.17" }
base64 = "0.22"
uuid = "1"
