[package]
name = "juniper_relay_helpers"
version = "0.1.0"
edition = "2024"

[dependencies]

juniper_relay_helpers_codegen = { path = "../juniper_relay_helpers_codegen" }
juniper = { workspace = true }
base64 = { workspace = true }
uuid = {  workspace = true, features = ["v4"] }
