[package]
name = "graphql-relay-helpers"
version = "0.1.0"
edition = "2024"

[dependencies]

graphql-relay-helpers-codegen = { path = "../graphql-relay-helpers-codegen" }
juniper = { workspace = true }
