name: 📦Publish Crate
on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Rust version
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }} && rustup component add clippy

      - name: Build
        run: make build-dev

      - name: Lint
        run: make lint

      - name: Unit Tests
        run: make test-unit

      - name: Integration Tests
        run: make test-integration

  publish_crate:
    name: Publish to Crates
    needs: build_and_test
    runs-on: ubuntu-latest
    environment: crates.io
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        run: cargo publish -p juniper_relay_helpers -p juniper_relay_helpers_codegen --verbose --no-verify --token ${{ secrets.CARGO_REGISTRY_TOKEN }}